# This file was generated by GoReleaser. DO NOT EDIT.
cask "pcp" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "c6601afb3f5e701a0bbb4467639a208f077c62ef25926a5cc43b37a29d8e0f4f"
      url "https://github.com/PatOConnor43/pcp/releases/download/v#{version}/pcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "71a99f5a19b3dfa01841c4539e4683f61fc8a3d4708a6c61f10668198fed31aa"
      url "https://github.com/PatOConnor43/pcp/releases/download/v#{version}/pcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4f4fb38bdd448e19a45714899d00ed1f923e49ece98b4ac91a049efd81afcbe9"
      url "https://github.com/PatOConnor43/pcp/releases/download/v#{version}/pcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8dc8beea17099c37d27eeb0f4364802e410994c623f0ce684b90da28e64f9a09"
      url "https://github.com/PatOConnor43/pcp/releases/download/v#{version}/pcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pcp"
  desc "Local reverse proxy that injects credentials so LLM agents can call APIs without handling secrets"
  homepage "https://github.com/PatOConnor43/pcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pcp"]
    end
  end

  # No zap stanza required
end
