# This file was generated by GoReleaser. DO NOT EDIT.
cask "pcp" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "14134eb46e9443d530c686de06339c1b7e205c3786442da5a72d72a097a4fd30"
      url "https://github.com/PatOConnor43/pcp/releases/download/v#{version}/pcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "57c38edcc9d585e0402efaf3d172bb8c95c6078ac60dcfc65fa52605ee582b55"
      url "https://github.com/PatOConnor43/pcp/releases/download/v#{version}/pcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0d97151aeb1d018ddde5751dc405818d7641bda05091777fa1c6da4cdb4dee72"
      url "https://github.com/PatOConnor43/pcp/releases/download/v#{version}/pcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a56e8cff3086ca44b589904c543395ec602f59a8f03b061498189843139d5359"
      url "https://github.com/PatOConnor43/pcp/releases/download/v#{version}/pcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pcp"
  desc "Local reverse proxy that injects credentials so LLM agents can call APIs without handling secrets"
  homepage "https://github.com/PatOConnor43/pcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pcp"]
    end
  end

  # No zap stanza required
end
