# This file was generated by GoReleaser. DO NOT EDIT.
cask "pcp" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "809a85fbc42497592be39f6c78c7a4ab282969142e2241c9312a3bfa715a4a79"
      url "https://github.com/PatOConnor43/pcp/releases/download/v#{version}/pcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c114f16cd5aaec8ae5bee289d3996c5e8ba68cf14192ed09e0339bf2eef6011d"
      url "https://github.com/PatOConnor43/pcp/releases/download/v#{version}/pcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9ccfcda803aa417ff9d44524e7c20580f51cfe47f0f01d3ab46864db75213ab6"
      url "https://github.com/PatOConnor43/pcp/releases/download/v#{version}/pcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0014ea42be439d54a1b03b1c7b5f138f14930eeb534ac256b94fbdc1cf3ea56f"
      url "https://github.com/PatOConnor43/pcp/releases/download/v#{version}/pcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pcp"
  desc "Local reverse proxy that injects credentials so LLM agents can call APIs without handling secrets"
  homepage "https://github.com/PatOConnor43/pcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pcp"]
    end
  end

  # No zap stanza required
end
